name: Code style

# This workflow runs code style checks.

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Code style
      run: |
        pip install pycodestyle
        pycodestyle urbanaccess
