name: Tests

# This workflow runs a suite of code style checks, unit tests, and integration tests.

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install UrbanAccess
      run: |
        pip install .
        conda list
    - name: Code style
      run: |
        pip install pycodestyle
        pycodestyle urbanaccess
    - name: Unit tests
      run: |
        pip install pytest
        pytest -s

#    - name: Demo notebook
#      run: |
#        conda install jupyter cartopy pyepsg --channel conda-forge
#        cd demo
#        jupyter nbconvert --to python simple_example.ipynb
#        cd ../urbanaccess/tests/integration
#        python remove_nb_magic.py -in simple_example.py -out simple_example_clean.py
#        cd ../../../demo
#        python simple_example_clean.py

#    - name: Integration tests
#      run: |
#        pip install cartopy
#        cd urbanaccess/tests/integration  # ../urbanaccess/tests/integration
#        python integration_madison.py
#        python integration_sandiego.py
